language: node_js
node_js: "10"


jobs: 
  include:
    - stage: Lint 
      script: npm run lint
    - stage: Build 
      script: npm run build 
    - stage: Deploy 
      script: npm run deploy 

branches:
  only:
    - master 

